#!/bin/bash

# 7.5 secs at 10kHz
POST=${POST:-75000}
let TLEN="$POST*120/100"

#(cd ~/PROJECTS/ACQ400/HAPI/acq400_hapi/user_apps/acq400;
# STATUSMONITOR_TRACE=0 ./acq400_capture.py --transient="PRE=0 POST=$TLEN SOFT_TRIGGER=1" acq2106_076
#)

(cd ~/PROJECTS/ACQ400/HAPI/acq400_hapi/user_apps/acq400;
./acq400_softtrigger.py acq2106_076
)
